### ISSUE TITLE
Deployment on Modulus gives error "Can't find npm module 'phantomjs'"

### ISSUE THREAD

**Issue by webstudiopro** [dfischer/meteor-phantomjs#1]
Hi,
When deploying on Modulus I got error "Can't find npm module 'phantomjs'" after all
So the package is not doing what it supposed to do
Do I miss something?
Thx
Benny

**Comment by dfischer** [comment]
Seems like a temporary error? Try again?

**Comment by webstudiopro** [comment]
Hi,
Seem we need latest version of Demeteorizer 
I did an update and everything is working as charme now !!!
Thx
Benny

**Comment by dfischer** [comment]
Great :+1:
