### ISSUE TITLE
spiderable: phantomjs failed: null  stderr: 

### ISSUE THREAD

**Issue by timmyg** [dfischer/meteor-phantomjs#2]
Getting the below error when I upload the project to Modulus.  Does it matter it is SSL?  Using Meteor 0.9.3.1.  Any tips for troubleshooting?

spiderable: phantomjs failed: null 
stderr:

**Comment by dfischer** [comment]
It's normal for it to error out a lot. At least for me. It works if I type ?_escaped_fragment_= at the end of my urls. Does that work for you?

I saw spiderable was just updated to handle ssl too. At least some edge cases regarding it.

**Comment by dfischer** [comment]
@timmyg pushed a new version, lmk if that helps?

**Comment by stevenhornung** [comment]
I'm still seeing this issue.  I posted a topic about it on meteor-talk at https://groups.google.com/forum/#!topic/meteor-talk/1m3DyDpFpQs

Do you have any idea if this would be a phantomjs issue or something else?  Like I mentioned in the post, we got rid of this issue awhile back but it came back up recently.

**Comment by dfischer** [comment]
Phantomjs/spiderable/meteor don't get along perfectly well. It fails all the time for me depending on how long it takes to render a page. It times out on modulus if it's over a certain time size.

**Comment by JulianKingman** [comment]
I'm seeing this error about 10-20 times per hour, any idea how to deal with this? What does it mean? It's very hard to read the server logs.

**Comment by dfischer** [comment]
It means it timed out rendering the page afaik

**Comment by JulianKingman** [comment]
Any ideas how to troubleshoot?
