### ISSUE TITLE
It does not seem to be working locally

### ISSUE THREAD

**Issue by fqborges** [dfischer/meteor-phantomjs#3]
I receive the following error in meteor out:
spiderable: phantomjs not installed. Download and install from http://phantomjs.org/ undefined

I am using a embeded custom version of the original phantomjs package and tried to raplace it by your package, but it seems to not be working locally. Any thoughts?

**Comment by dfischer** [comment]
Not sure. This package installs phantomjs via an NPM binary. What OS are you on? Also... have you tried on Modulus? I think locally I still use `brew install phantomjs`

**Comment by fqborges** [comment]
I am using Ubuntu 14.04 64bits.

On Mon, Oct 13, 2014 at 5:52 PM, Daniel Fischer notifications@github.com
wrote:

> Not sure. This package installs phantomjs via an NPM binary. What OS are
> you on?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dfischer/meteor-phantomjs/issues/3#issuecomment-58953121
> .

## 

Filipe Quadros Borges

**Comment by dfischer** [comment]
Locally I would just use apt-get install phantomjs then and spiderable will use that package. This one definitely works on the modulus.io platform and that's what I use it for.

**Comment by fqborges** [comment]
thanks for your reply, i will try that.

On Mon, Oct 13, 2014 at 8:59 PM, Daniel Fischer notifications@github.com
wrote:

> Locally I would just use apt-get install phantomjs then and spiderable
> will use that package. This one definitely works on the modulus.io
> platform and that's what I use it for.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dfischer/meteor-phantomjs/issues/3#issuecomment-58972121
> .

## 

Filipe Quadros Borges
