### ISSUE TITLE
The latest commit is not on atmosphere

### ISSUE THREAD

**Issue by bstocks** [dfischer/meteor-phantomjs#5]
I just verified that the latest code commit that got this working with 1.0 doesn't seem to be up on Atmosphere. It looks like you need to give the package a version bump for Atmosphere to accept the changes.

**Comment by dfischer** [comment]
Investigating

**Comment by dfischer** [comment]
Should be done now. Can you let me know @bstocks ?

**Comment by bstocks** [comment]
Looks good, thanks!
