### ISSUE TITLE
Error: Cannot find module 'phantomjs' 

### ISSUE THREAD

**Issue by stlouisweb** [dfischer/meteor-phantomjs#7]
I get this when I try to sue Phantom in my project like so:

``` javascript
    var phantomjs = Npm.require('phantomjs');
    var spawn = Npm.require('child_process').spawn;
    command = spawn(phantomjs.path, ['assets/app/waitNrasterize.js', reportLink, filename, 'A4']);
    result = filename;
    command.on('exit', function () { callback(null, result); });
```

**Comment by SeanBannister** [comment]
I also experienced this error, and as I was trying to debug it it magically went away :| I'm wondering if restarting Meteor multiple times fixed it.

**Comment by stlouisweb** [comment]
yea interesting that this was closed with no explanation or update of a bugifx? Would be helpful to provide users that come to this page, of the work around or correct package to use since this one doesn't work.
