### ISSUE TITLE
Not working on Modulus

### ISSUE THREAD

**Issue by charleshan** [dfischer/meteor-phantomjs#8]
`/?_escaped_fragment_=` works locally but gets errors on Modulus. I have tried the combinations of the packages below:

`dfischer:phantomjs` + `ongoworks:spiderable`:

```
spiderable: phantomjs failed: Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5) 
stderr:
```

`dfischer:phantomjs` + `spiderable`:

```
spiderable: phantomjs failed: Error: Command failed: Can't open '/dev/stdin'

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5) 
stderr: Can't open '/dev/stdin'
```

**Comment by sergical** [comment]
+1 on the `dfischer:phantomjs + spiderable:` combo getting that error on Modulus however it's not crashing the app

**Comment by charleshan** [comment]
I found out that it was a problem related to other packages.

**Comment by sergical** [comment]
@OminStyle it would be nice if you shared what the problem was and what fix was applied, thanks!

**Comment by charleshan** [comment]
`materialize:materialize` package was causing the problem. Here is my temporary solution: https://github.com/Dogfalo/materialize/issues/1805. I hope it helps.

**Comment by sergical** [comment]
hmmm, not using materialize. not sure what other package would be causing that, is there a way to check?

Sincerely,
Sergiy Dybskiy

Sent from my iPhone

On Aug 20, 2015, at 8:46 PM, Charles Han <notifications@github.com<mailto:notifications@github.com>> wrote:

materialize:materialize package was causing the problem. Here is my temporary solution: Dogfalo/materialize#1805https://github.com/Dogfalo/materialize/issues/1805. I hope it helps.

##

**Comment by charleshan** [comment]
Yes... Well you have to manually check them one by one. Maybe not exactly one by one. Split in half, check if it breaks. If it does, split in half again and repeat.

**Comment by sergical** [comment]
Thanks :)
